version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/dreamfusion-0.0.1-SNAPSHOT.jar
  discard-paths: yes














